### ISSUE TITLE
php54-apache-imagemagick

### ISSUE THREAD

**Issue by T-baby** [Profideo/docker-images#15]
ImageMagick is not visible in phpinfo ？

**Comment by fsevestre** [comment]
Hi @T-baby, I'm sorry but the Docker images we provide in this repo are not meant to be used by someone outside our organization. We don't have a BC promise (yet at least) and I can't promise you that we won't break everything in the near future.
I posted the issue on our Slack to find a solution.

**Comment by sowbiba** [comment]
https://github.com/Profideo/docker-images/blob/master/README.md
